"""Alembic environment configuration for database migrations.

Purpose: Configure Alembic's migration runner to detect schema changes,
generate migration scripts, and apply them to PostgreSQL.

Responsibility: Load SQLAlchemy Base.metadata, configure database URL,
implement run_migrations_online() for async execution.

Consumers: Alembic CLI (`alembic upgrade head`), CI/CD deployment pipeline.

Restrictions: This file is generated by Alembic; modifications require
understanding of Alembic's environment setup pattern.

Reference: Alembic documentation (https://alembic.sqlalchemy.org/en/latest/)
"""

import asyncio
import logging
from logging.config import fileConfig

from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from alembic import context

# Load Alembic configuration
config = context.config

# Load Python logging config (if present in alembic.ini)
if config.config_file_name is not None:
    fileConfig(config.config_file_name)

logger = logging.getLogger("alembic.env")

# Load SQLAlchemy Base metadata
from database.base import Base

target_metadata = Base.metadata


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode (without connecting to DB).

    Purpose: For environments where live DB connection isn't available
    or for generating migration scripts for review.

    This mode generates SQL statements without executing them.
    Typically used for: script generation, code review, CI/CD planning.
    """

    url = config.get_main_option("sqlalchemy.url")
    context.configure(
        url=url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )

    with context.begin_transaction():
        context.run_migrations()
        logger.info("Offline migrations completed")


def do_run_migrations(connection: Connection) -> None:
    """Execute migrations with a live database connection.

    Args:
        connection: SQLAlchemy sync connection to database.
    """

    context.configure(connection=connection, target_metadata=target_metadata)

    with context.begin_transaction():
        context.run_migrations()
        logger.info("Migrations applied to database")


async def run_migrations_online() -> None:
    """Run migrations in 'online' mode (with live DB connection).

    Purpose: For production deployments where async engine is preferred.

    This is the standard migration path:
        1. Create async engine from configuration
        2. Connect to database
        3. Run all pending migrations
        4. Disconnect

    Called by: CLI (`alembic upgrade head`), deployment scripts.
    """

    # Get database URL from config
    configuration = config.get_section(config.config_ini_section)
    configuration["sqlalchemy.url"] = configuration.get(
        "sqlalchemy.url", "postgresql+asyncpg://localhost/mif_copilot"
    )

    # Create async engine
    connectable = create_async_engine(
        configuration["sqlalchemy.url"],
        poolclass=pool.NullPool,  # No pooling for migrations
        echo=False,
    )

    # Run migrations
    async with connectable.begin() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()
    logger.info("Online migrations completed")


# Determine execution mode (online vs offline)
if context.is_offline_mode():
    logger.info("Running migrations in offline mode")
    run_migrations_offline()
else:
    logger.info("Running migrations in online mode")
    asyncio.run(run_migrations_online())

