"""Shared primitives package.

This package provides the foundational types, constants, exceptions, validators, and formatters
used throughout the MIF Infrastructure Copilot application. All exports are production-quality,
zero external dependencies (beyond stdlib), and immutable where required.

Shared is a leaf package in the hexagonal architecture: no other package in shared/ may be imported.
All other layers depend on shared/ for core primitives.

Reference: doc/02_BACKEND_MODULE_ARCHITECTURE.md §2.1 (Layer Model)
          Decisions.md §4 (Dependency Rules)
"""

# Types (domain models)
from .types import (
    DraftState,
    GlueJobConfig,
    GitHubToken,
    PRMetadata,
    RepositoryFacts,
    ValidationResult,
)

# Constants (application-wide values)
from .constants import (
    DEFAULT_CATALOG,
    DEFAULT_ASSUME_SESSION_NAME,
    DEFAULT_ENTERPRISE_FUNCTION,
    DEFAULT_ENVIRONMENT,
    DEFAULT_GLUE_VERSION,
    DEFAULT_JOB_TYPE,
    DEFAULT_JOB_VERSION,
    DEFAULT_SCHEDULING_MODE,
    DEFAULT_SINK_TYPE,
    DEFAULT_SOURCE_TYPE,
    DEFAULT_SUBGROUP,
    DEFAULT_WORKER_COUNT,
    DEFAULT_WORKER_TYPE,
    DRAFT_RETENTION_DAYS,
    DRAFT_STATUSES,
    DRAFT_STATUS_VALUES,
    ENTERPRISE_FUNCTIONS,
    ENTERPRISE_FUNCTION_VALUES,
    ENVIRONMENT_VALUES,
    ENVIRONMENTS,
    GLUE_VERSION_VALUES,
    JOB_RULE_PREFIX,
    JOB_TYPES,
    JOB_TYPE_VALUES,
    KAFKA_SECRET_PATTERN,
    MAX_WORKER_COUNT,
    OPERATION_TYPES,
    OPERATION_TYPE_VALUES,
    PHASE1_SOURCE_TYPES,
    RATE_LIMIT_REQUESTS_PER_MINUTE,
    RATE_LIMIT_WINDOW_SECONDS,
    SCHEDULING_MODES,
    SCHEDULING_MODE_VALUES,
    SESSION_EXPIRY_HOURS,
    SINK_TRIGGER,
    SNAPSHOT_RETENTION_DAYS,
    SOURCE_TYPES,
    SOURCE_TYPE_VALUES,
    STOP_BEFORE_START,
    SUBGROUPS,
    SUBGROUP_VALUES,
    TERRAFORM_FMT_ARGS,
    TERRAFORM_INIT_ARGS,
    TERRAFORM_RULE_PREFIX,
    TERRAFORM_VALIDATE_ARGS,
    TERRAFORM_VALIDATION_TIMEOUT_SECONDS,
    TOPIC_NAME_PATTERN,
    TOPIC_RULE_PREFIX,
    WORKER_TYPES,
    WORKER_TYPE_VALUES,
    JOB_NAME_PATTERN,
    BRANCH_NAME_PATTERN,
    VALIDATION_MESSAGE_TEMPLATES,
)

# Exceptions (error hierarchy)
from .exceptions import (
    ApplicationException,
    AuthenticationException,
    ConflictException,
    CopilotException,
    DerivationException,
    DraftException,
    GitHubException,
    KnowledgeException,
    ParserException,
    PRException,
    PriorityResolutionException,
    RegistryLoadException,
    RegistryValidationException,
    RepositoryException,
    SessionException,
    TemplateRenderException,
    TerraformException,
    ValidationException,
)

# Validators (pure validation functions)
from .validators import (
    validate_job_name_format,
    validate_schema_grain_format,
    validate_source_system_name,
    validate_topic_format,
)

# Formatters (pure formatting functions)
from .formatters import (
    format_git_branch_name,
    format_glue_job_name,
    format_iso8601_datetime,
    format_kafka_secret_name,
    format_pr_title,
    format_terraform_path,
    format_topic_name,
)

__all__ = [
    # Types
    "DraftState",
    "GlueJobConfig",
    "GitHubToken",
    "PRMetadata",
    "RepositoryFacts",
    "ValidationResult",
    # Constants - environment, worker, job, enterprise
    "DEFAULT_CATALOG",
    "DEFAULT_ASSUME_SESSION_NAME",
    "DEFAULT_ENTERPRISE_FUNCTION",
    "DEFAULT_ENVIRONMENT",
    "DEFAULT_GLUE_VERSION",
    "DEFAULT_JOB_TYPE",
    "DEFAULT_JOB_VERSION",
    "DEFAULT_SCHEDULING_MODE",
    "DEFAULT_SINK_TYPE",
    "DEFAULT_SOURCE_TYPE",
    "DEFAULT_SUBGROUP",
    "DEFAULT_WORKER_COUNT",
    "DEFAULT_WORKER_TYPE",
    "DRAFT_RETENTION_DAYS",
    "DRAFT_STATUSES",
    "DRAFT_STATUS_VALUES",
    "ENTERPRISE_FUNCTIONS",
    "ENTERPRISE_FUNCTION_VALUES",
    "ENVIRONMENT_VALUES",
    "ENVIRONMENTS",
    "GLUE_VERSION_VALUES",
    "JOB_RULE_PREFIX",
    "JOB_TYPES",
    "JOB_TYPE_VALUES",
    "KAFKA_SECRET_PATTERN",
    "MAX_WORKER_COUNT",
    "OPERATION_TYPES",
    "OPERATION_TYPE_VALUES",
    "PHASE1_SOURCE_TYPES",
    "RATE_LIMIT_REQUESTS_PER_MINUTE",
    "RATE_LIMIT_WINDOW_SECONDS",
    "SCHEDULING_MODES",
    "SCHEDULING_MODE_VALUES",
    "SESSION_EXPIRY_HOURS",
    "SINK_TRIGGER",
    "SNAPSHOT_RETENTION_DAYS",
    "SOURCE_TYPES",
    "SOURCE_TYPE_VALUES",
    "STOP_BEFORE_START",
    "SUBGROUPS",
    "SUBGROUP_VALUES",
    "TERRAFORM_FMT_ARGS",
    "TERRAFORM_INIT_ARGS",
    "TERRAFORM_RULE_PREFIX",
    "TERRAFORM_VALIDATE_ARGS",
    "TERRAFORM_VALIDATION_TIMEOUT_SECONDS",
    "TOPIC_NAME_PATTERN",
    "TOPIC_RULE_PREFIX",
    "WORKER_TYPES",
    "WORKER_TYPE_VALUES",
    "JOB_NAME_PATTERN",
    "BRANCH_NAME_PATTERN",
    "VALIDATION_MESSAGE_TEMPLATES",
    # Exceptions
    "ApplicationException",
    "AuthenticationException",
    "ConflictException",
    "CopilotException",
    "DerivationException",
    "DraftException",
    "GitHubException",
    "KnowledgeException",
    "ParserException",
    "PRException",
    "PriorityResolutionException",
    "RegistryLoadException",
    "RegistryValidationException",
    "RepositoryException",
    "SessionException",
    "TemplateRenderException",
    "TerraformException",
    "ValidationException",
    # Validators
    "validate_job_name_format",
    "validate_schema_grain_format",
    "validate_source_system_name",
    "validate_topic_format",
    # Formatters
    "format_git_branch_name",
    "format_glue_job_name",
    "format_iso8601_datetime",
    "format_kafka_secret_name",
    "format_pr_title",
    "format_terraform_path",
    "format_topic_name",
]
